"""create booking tables

Revision ID: 73590898a60e
Revises: 
Create Date: 2026-03-26 17:46:05.019007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73590898a60e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('passenger_name', sa.String(length=255), nullable=False),
    sa.Column('flight_number', sa.String(length=50), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_pickup_time_status', 'booking', ['pickup_time', 'status'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_status_history_booking_id', 'booking_status_history', ['booking_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_log_booking_id', 'notification_log', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop child tables first so their FK constraints are removed before the parent.
    # MySQL drops all indexes automatically when a table is dropped, so explicit
    # index drops are omitted to avoid "index used by FK constraint" errors.
    op.drop_table('notification_log')
    op.drop_table('booking_status_history')
    op.drop_index('ix_booking_pickup_time_status', table_name='booking')
    op.drop_table('booking')
